%% Script to define the growth functions as part of "Exact solutions for diffusive
%% transport on heterogeneous growing domains" by Johnston and Simpson, 2023.

if strcmpi(growthType,'linear')
    
    % Domain growth function, single transform function and double
    % transform function for linear growth.
    domainGrowthFunction = @(t,n) L0(n)+beta(n)*t;
    transformFunction = @(t,n) L0(n)/(L0(n)+beta(n)*t)*t;
    relativeTransformFunction = @(t1,t2,n) (L0(n)+beta(n)*t1)/(L0(n)+beta(n)*t2)*(t2-t1);
    
elseif strcmpi(growthType,'exponential')
    
    % Domain growth function, single transform function and double
    % transform function for exponential growth.
    domainGrowthFunction = @(t,n) (L0(n)-minL(n))*exp(-beta(n)*t)+minL(n);
    transformFunction = @(t,n) L0(n)^2/(minL(n)^2*beta(n))*(minL(n)/L0(n) - 1 + 1/(1 + minL(n)/(L0(n)-minL(n)) * exp(beta(n)*t)) - ...
        log(L0(n)) + log(L0(n)+minL(n)*(exp(beta(n)*t)-1)));
    relativeTransformFunction = @(t1,t2,n) (exp(-beta(n)*t1)*(L0(n)-minL(n))+minL(n))^2 * ...
                ((L0(n)-minL(n))*(1/(-L0(n)+minL(n)-minL(n)*exp(beta(n)*t1))+1/(L0(n)-minL(n)+minL(n)*exp(beta(n)*t2))) - ...
                log(L0(n)+minL(n)*(exp(beta(n)*t1)-1)) + log(L0(n)+minL(n)*(exp(beta(n)*t2)-1)))/(beta(n)*minL(n)^2);
    
elseif strcmpi(growthType,'oscillating')
    
    % Domain growth function, single transform function and double
    % transform function for oscillating growth.   
    domainGrowthFunction = @(t,n) L0(n) + (L0(n)-minL(n))*sin(beta(n)*t);
    transformFunction = @(t,n) (L0(n)+(L0(n)-minL(n))*sin(beta(n)*0))/...
        (beta(n)*minL(n)*(2*L0(n)-minL(n))*sqrt(L0(n)^2-(L0(n)-minL(n))^2)*(L0(n)+(L0(n)-minL(n))*sin(beta(n)*t))) * ...
        ((L0(n)-minL(n))*sqrt(L0(n)^2-(L0(n)-minL(n))^2)* ...
        (cos(beta(n)*t)*(L0(n)+(L0(n)-minL(n))*sin(beta(n)*0)) - cos(beta(n)*0)*(L0(n)+(L0(n)-minL(n))*sin(beta(n)*t))) + ...
        2*L0(n)*(L0(n)+(L0(n)-minL(n))*sin(beta(n)*0))*(L0(n)+(L0(n)-minL(n))*sin(beta(n)*t)) * ...
        (atan((L0(n)*(tan(beta(n)*t/2)+1)-minL(n))/sqrt(L0(n)^2-(L0(n)-minL(n))^2)) - ...
        atan((L0(n)*(tan(beta(n)*0/2)+1)-minL(n))/sqrt(L0(n)^2-(L0(n)-minL(n))^2)))) + ...
        (L0(n)+(L0(n)-minL(n))*sin(beta(n)*0))^2 * ...
        (2*pi/beta(n)*L0(n)/(L0(n)^2-(L0(n)-minL(n))^2)^(3/2)*floor((beta(n)*t+pi)/(2*pi)));
    relativeTransformFunction = @(t1,t2,n) (L0(n)+(L0(n)-minL(n))*sin(beta(n)*t1))/...
        (beta(n)*minL(n)*(2*L0(n)-minL(n))*sqrt(L0(n)^2-(L0(n)-minL(n))^2)*(L0(n)+(L0(n)-minL(n))*sin(beta(n)*t2))) * ...
        ((L0(n)-minL(n))*sqrt(L0(n)^2-(L0(n)-minL(n))^2)* ...
        (cos(beta(n)*t2)*(L0(n)+(L0(n)-minL(n))*sin(beta(n)*t1)) - cos(beta(n)*t1)*(L0(n)+(L0(n)-minL(n))*sin(beta(n)*t2))) + ...
        2*L0(n)*(L0(n)+(L0(n)-minL(n))*sin(beta(n)*t1))*(L0(n)+(L0(n)-minL(n))*sin(beta(n)*t2)) * ...
        (atan((L0(n)*(tan(beta(n)*t2/2)+1)-minL(n))/sqrt(L0(n)^2-(L0(n)-minL(n))^2)) - ...
        atan((L0(n)*(tan(beta(n)*t1/2)+1)-minL(n))/sqrt(L0(n)^2-(L0(n)-minL(n))^2)))) + ...
        (L0(n)+(L0(n)-minL(n))*sin(beta(n)*t1))^2 * ...
        (2*pi/beta(n)*L0(n)/(L0(n)^2-(L0(n)-minL(n))^2)^(3/2)*(floor((beta(n)*t2+pi)/(2*pi))-floor((beta(n)*t1+pi)/(2*pi))));
    
else
    
    % Ensure that an appropriate growth function is chosen.
    error('Incorrect choice of growth function');
    
end